baseURL = "https://hauru.eu/"
theme = "hauru"

title = "Tomek Paczkowski"
description = "Tomek Paczkowski - Principal Software Engineer"
# This message is only used by the RSS template
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

languageCode = "en-gb"
defaultContentLanguage = "en"
enableEmoji = true            # https://gohugo.io/functions/emojify/

paginate = 25

disableKinds = [ "taxonomy", "sitemap", "RSS" ]

[taxonomies]
tag = "tags"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

# This is used in the page footer
footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params.author]
name = "Tomek Paczkowski"

[markup.goldmark.renderer]
unsafe = true

[menu]

#   [[menu.main]]
#     name = "Posts"
#     url = "posts/"
#     weight = 10

#   [[menu.main]]
#     name = "About"
#     url = "about-hugo/"
#     weight = 20
