[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/js/*.min.*.js"
    [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/css/*.min.*.css"
    [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/fonts/*.woff2"
    [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
    Access-Control-Allow-Origin = "*"
